language: java
jdk:
  - oraclejdk8

install:
- ./gradlew install

script:
- ./gradlew check
- ./gradlew -p acceptance-test test

after_success:
- test ${TRAVIS_TAG} -a ${BINTRAY} && ./gradlew -Pversion=${TRAVIS_TAG#v} bintrayUpload

env:
  global:
  - TERM=dumb
